#!/bin/bash 

    java -classpath /home/berto/ASP/PDDL+/ENHSP-Public-master/src/:/home/berto/ASP/PDDL+/ENHSP-Public-master/libs/PPMaJal2.jar:/home/berto/ASP/PDDL+/ENHSP-Public-master/libs/* ENHSP "$@"
